import type { Template } from '../types';

export const STORY_TEMPLATES: Template[] = [
  {
    id: 'three-act',
    name: 'templates.threeAct.name',
    description: 'templates.threeAct.description',
    type: 'Structure',
    tags: ['tags.classic', 'tags.plotDriven', 'tags.beginnerFriendly'],
    arcDescription: 'templates.threeAct.arc',
    sections: [
      { titleKey: 'templates.threeAct.sections.1' },
      { titleKey: 'templates.threeAct.sections.2' },
      { titleKey: 'templates.threeAct.sections.3' },
      { titleKey: 'templates.threeAct.sections.4' },
      { titleKey: 'templates.threeAct.sections.5' },
      { titleKey: 'templates.threeAct.sections.6' },
      { titleKey: 'templates.threeAct.sections.7' },
      { titleKey: 'templates.threeAct.sections.8' },
      { titleKey: 'templates.threeAct.sections.9' },
      { titleKey: 'templates.threeAct.sections.10' },
    ],
  },
  {
    id: 'heros-journey',
    name: 'templates.herosJourney.name',
    description: 'templates.herosJourney.description',
    type: 'Structure',
    tags: ['tags.classic', 'tags.characterDriven', 'tags.epic'],
    arcDescription: 'templates.herosJourney.arc',
    sections: [
      { titleKey: 'templates.herosJourney.sections.1' },
      { titleKey: 'templates.herosJourney.sections.2' },
      { titleKey: 'templates.herosJourney.sections.3' },
      { titleKey: 'templates.herosJourney.sections.4' },
      { titleKey: 'templates.herosJourney.sections.5' },
      { titleKey: 'templates.herosJourney.sections.6' },
      { titleKey: 'templates.herosJourney.sections.7' },
      { titleKey: 'templates.herosJourney.sections.8' },
      { titleKey: 'templates.herosJourney.sections.9' },
      { titleKey: 'templates.herosJourney.sections.10' },
      { titleKey: 'templates.herosJourney.sections.11' },
      { titleKey: 'templates.herosJourney.sections.12' },
    ],
  },
  {
    id: 'save-the-cat',
    name: 'templates.saveTheCat.name',
    description: 'templates.saveTheCat.description',
    type: 'Structure',
    tags: ['tags.screenwriting', 'tags.plotDriven', 'tags.commercial'],
    arcDescription: 'templates.saveTheCat.arc',
    sections: [
      { titleKey: 'templates.saveTheCat.sections.1' },
      { titleKey: 'templates.saveTheCat.sections.2' },
      { titleKey: 'templates.saveTheCat.sections.3' },
      { titleKey: 'templates.saveTheCat.sections.4' },
      { titleKey: 'templates.saveTheCat.sections.5' },
      { titleKey: 'templates.saveTheCat.sections.6' },
      { titleKey: 'templates.saveTheCat.sections.7' },
      { titleKey: 'templates.saveTheCat.sections.8' },
      { titleKey: 'templates.saveTheCat.sections.9' },
      { titleKey: 'templates.saveTheCat.sections.10' },
      { titleKey: 'templates.saveTheCat.sections.11' },
      { titleKey: 'templates.saveTheCat.sections.12' },
      { titleKey: 'templates.saveTheCat.sections.13' },
      { titleKey: 'templates.saveTheCat.sections.14' },
      { titleKey: 'templates.saveTheCat.sections.15' },
    ],
  },
  {
    id: 'fichtean-curve',
    name: 'templates.fichteanCurve.name',
    description: 'templates.fichteanCurve.description',
    type: 'Structure',
    tags: ['tags.fastPaced', 'tags.thriller', 'tags.inMediaRes'],
    arcDescription: 'templates.fichteanCurve.arc',
    sections: [
      { titleKey: 'templates.fichteanCurve.sections.1' },
      { titleKey: 'templates.fichteanCurve.sections.2' },
      { titleKey: 'templates.fichteanCurve.sections.3' },
      { titleKey: 'templates.fichteanCurve.sections.4' },
      { titleKey: 'templates.fichteanCurve.sections.5' },
      { titleKey: 'templates.fichteanCurve.sections.6' },
    ],
  },
  {
    id: 'murder-mystery',
    name: 'templates.murderMystery.name',
    description: 'templates.murderMystery.description',
    type: 'Genre',
    tags: ['tags.plotDriven', 'tags.investigation', 'tags.suspense'],
    arcDescription: 'templates.murderMystery.arc',
    sections: [
      { titleKey: 'templates.murderMystery.sections.1' },
      { titleKey: 'templates.murderMystery.sections.2' },
      { titleKey: 'templates.murderMystery.sections.3' },
      { titleKey: 'templates.murderMystery.sections.4' },
      { titleKey: 'templates.murderMystery.sections.5' },
      { titleKey: 'templates.murderMystery.sections.6' },
      { titleKey: 'templates.murderMystery.sections.7' },
      { titleKey: 'templates.murderMystery.sections.8' },
      { titleKey: 'templates.murderMystery.sections.9' },
      { titleKey: 'templates.murderMystery.sections.10' },
    ],
  },
  {
    id: 'space-opera',
    name: 'templates.spaceOpera.name',
    description: 'templates.spaceOpera.description',
    type: 'Genre',
    tags: ['tags.sciFi', 'tags.epic', 'tags.adventure'],
    arcDescription: 'templates.spaceOpera.arc',
    sections: [
      { titleKey: 'templates.spaceOpera.sections.1' },
      { titleKey: 'templates.spaceOpera.sections.2' },
      { titleKey: 'templates.spaceOpera.sections.3' },
      { titleKey: 'templates.spaceOpera.sections.4' },
      { titleKey: 'templates.spaceOpera.sections.5' },
      { titleKey: 'templates.spaceOpera.sections.6' },
      { titleKey: 'templates.spaceOpera.sections.7' },
      { titleKey: 'templates.spaceOpera.sections.8' },
      { titleKey: 'templates.spaceOpera.sections.9' },
      { titleKey: 'templates.spaceOpera.sections.10' },
      { titleKey: 'templates.spaceOpera.sections.11' },
    ],
  },
  {
    id: 'dystopian-fiction',
    name: 'templates.dystopian.name',
    description: 'templates.dystopian.description',
    type: 'Genre',
    tags: ['tags.sciFi', 'tags.socialCommentary', 'tags.rebellion'],
    arcDescription: 'templates.dystopian.arc',
    sections: [
      { titleKey: 'templates.dystopian.sections.1' },
      { titleKey: 'templates.dystopian.sections.2' },
      { titleKey: 'templates.dystopian.sections.3' },
      { titleKey: 'templates.dystopian.sections.4' },
      { titleKey: 'templates.dystopian.sections.5' },
      { titleKey: 'templates.dystopian.sections.6' },
      { titleKey: 'templates.dystopian.sections.7' },
      { titleKey: 'templates.dystopian.sections.8' },
      { titleKey: 'templates.dystopian.sections.9' },
    ],
  },
  {
    id: 'classic-romance',
    name: 'templates.romance.name',
    description: 'templates.romance.description',
    type: 'Genre',
    tags: ['tags.characterDriven', 'tags.romance', 'tags.emotional'],
    arcDescription: 'templates.romance.arc',
    sections: [
      { titleKey: 'templates.romance.sections.1' },
      { titleKey: 'templates.romance.sections.2' },
      { titleKey: 'templates.romance.sections.3' },
      { titleKey: 'templates.romance.sections.4' },
      { titleKey: 'templates.romance.sections.5' },
      { titleKey: 'templates.romance.sections.6' },
      { titleKey: 'templates.romance.sections.7' },
      { titleKey: 'templates.romance.sections.8' },
    ],
  },
  {
    id: 'thriller',
    name: 'templates.thriller.name',
    description: 'templates.thriller.description',
    type: 'Genre',
    tags: ['tags.suspense', 'tags.plotDriven', 'tags.fastPaced'],
    arcDescription: 'templates.thriller.arc',
    sections: [
      { titleKey: 'templates.thriller.sections.1' },
      { titleKey: 'templates.thriller.sections.2' },
      { titleKey: 'templates.thriller.sections.3' },
      { titleKey: 'templates.thriller.sections.4' },
      { titleKey: 'templates.thriller.sections.5' },
      { titleKey: 'templates.thriller.sections.6' },
      { titleKey: 'templates.thriller.sections.7' },
    ],
  },
  {
    id: 'fantasy',
    name: 'templates.fantasy.name',
    description: 'templates.fantasy.description',
    type: 'Genre',
    tags: ['tags.epic', 'tags.adventure', 'tags.characterDriven'],
    arcDescription: 'templates.fantasy.arc',
    sections: [
      { titleKey: 'templates.fantasy.sections.1' },
      { titleKey: 'templates.fantasy.sections.2' },
      { titleKey: 'templates.fantasy.sections.3' },
      { titleKey: 'templates.fantasy.sections.4' },
      { titleKey: 'templates.fantasy.sections.5' },
      { titleKey: 'templates.fantasy.sections.6' },
      { titleKey: 'templates.fantasy.sections.7' },
      { titleKey: 'templates.fantasy.sections.8' },
    ],
  },
  {
    id: 'horror',
    name: 'templates.horror.name',
    description: 'templates.horror.description',
    type: 'Genre',
    tags: ['tags.suspense', 'tags.plotDriven'],
    arcDescription: 'templates.horror.arc',
    sections: [
      { titleKey: 'templates.horror.sections.1' },
      { titleKey: 'templates.horror.sections.2' },
      { titleKey: 'templates.horror.sections.3' },
      { titleKey: 'templates.horror.sections.4' },
      { titleKey: 'templates.horror.sections.5' },
      { titleKey: 'templates.horror.sections.6' },
      { titleKey: 'templates.horror.sections.7' },
    ],
  },
  {
    id: 'historical-fiction',
    name: 'templates.historical.name',
    description: 'templates.historical.description',
    type: 'Genre',
    tags: ['tags.characterDriven', 'tags.emotional'],
    arcDescription: 'templates.historical.arc',
    sections: [
      { titleKey: 'templates.historical.sections.1' },
      { titleKey: 'templates.historical.sections.2' },
      { titleKey: 'templates.historical.sections.3' },
      { titleKey: 'templates.historical.sections.4' },
      { titleKey: 'templates.historical.sections.5' },
      { titleKey: 'templates.historical.sections.6' },
    ],
  },
  {
    id: 'coming-of-age',
    name: 'templates.comingOfAge.name',
    description: 'templates.comingOfAge.description',
    type: 'Genre',
    tags: ['tags.characterDriven', 'tags.emotional'],
    arcDescription: 'templates.comingOfAge.arc',
    sections: [
      { titleKey: 'templates.comingOfAge.sections.1' },
      { titleKey: 'templates.comingOfAge.sections.2' },
      { titleKey: 'templates.comingOfAge.sections.3' },
      { titleKey: 'templates.comingOfAge.sections.4' },
      { titleKey: 'templates.comingOfAge.sections.5' },
      { titleKey: 'templates.comingOfAge.sections.6' },
    ],
  },
  {
    id: 'adventure',
    name: 'templates.adventure.name',
    description: 'templates.adventure.description',
    type: 'Genre',
    tags: ['tags.adventure', 'tags.fastPaced', 'tags.plotDriven'],
    arcDescription: 'templates.adventure.arc',
    sections: [
      { titleKey: 'templates.adventure.sections.1' },
      { titleKey: 'templates.adventure.sections.2' },
      { titleKey: 'templates.adventure.sections.3' },
      { titleKey: 'templates.adventure.sections.4' },
      { titleKey: 'templates.adventure.sections.5' },
      { titleKey: 'templates.adventure.sections.6' },
    ],
  },
  {
    id: 'mystery',
    name: 'templates.mystery.name',
    description: 'templates.mystery.description',
    type: 'Genre',
    tags: ['tags.investigation', 'tags.suspense', 'tags.plotDriven'],
    arcDescription: 'templates.mystery.arc',
    sections: [
      { titleKey: 'templates.mystery.sections.1' },
      { titleKey: 'templates.mystery.sections.2' },
      { titleKey: 'templates.mystery.sections.3' },
      { titleKey: 'templates.mystery.sections.4' },
      { titleKey: 'templates.mystery.sections.5' },
      { titleKey: 'templates.mystery.sections.6' },
    ],
  },
];
