/**
 * StyleAdaptedWriterAgent — Optional ProForge agent using an active LoRA adapter.
 * QNBS-v3: Extends BaseAgent; inserts after 'lineProse' via PipelineStageExtension.
 *          Produces proseEdit review items generated by the user's personal style model.
 *          Returns a fallback (isFallback: true) when no adapter is active.
 */

import { v4 as uuid } from 'uuid';
import type { ReviewItem, StageResult } from '../../../features/proForge/types';
import { generateLocalText } from '../../localAiFacade';
import { logger } from '../../logger';
import { getActiveAdapter } from '../../loraAdapterService';
import { BaseAgent } from './baseAgent';

export class StyleAdaptedWriterAgent extends BaseAgent {
  async execute(
    signal: AbortSignal,
  ): Promise<Pick<StageResult, 'reviewItems' | 'metrics' | 'agentOutput'>> {
    const startTime = performance.now();

    // Resolve active adapter from IDB (not Redux — agents run outside React lifecycle)
    const activeAdapter = await getActiveAdapter();

    if (!activeAdapter) {
      logger.info('StyleAdaptedWriterAgent: no active LoRA adapter — returning fallback');
      return {
        reviewItems: [],
        metrics: {
          aiCalls: 0,
          tokensConsumed: 0,
          durationMs: this.elapsed(startTime),
          itemsFound: 0,
          itemsAccepted: 0,
          itemsRejected: 0,
        },
        agentOutput: { isFallback: true, reason: 'no_active_adapter' },
      };
    }

    if (signal.aborted) {
      return {
        reviewItems: [],
        metrics: {
          aiCalls: 0,
          tokensConsumed: 0,
          durationMs: 0,
          itemsFound: 0,
          itemsAccepted: 0,
          itemsRejected: 0,
        },
        agentOutput: { isFallback: true, reason: 'aborted' },
      };
    }

    const project = this.requireProject();
    const sections = project.manuscript ?? [];
    const reviewItems: ReviewItem[] = [];
    let aiCalls = 0;
    let tokensConsumed = 0;

    for (const section of sections.slice(0, 3)) {
      if (signal.aborted) break;
      const text = section.content ?? '';
      if (text.length < 200) continue;

      const prompt = `You are a style-adapted writing assistant trained on this author's voice. Suggest one improvement to this passage that preserves the author's style while enhancing prose quality:\n\n${text.slice(0, 800)}`;

      try {
        const response = await generateLocalText(
          prompt,
          activeAdapter.modelCompatibility,
          undefined,
          activeAdapter.id,
        );
        const suggestion = response?.text ?? '';
        if (suggestion.length > 50) {
          reviewItems.push({
            id: uuid(),
            stage: 'lineProse' as const,
            type: 'proseEdit',
            severity: 'info',
            status: 'pending',
            sectionId: section.id,
            description: `Style-adapted suggestion from ${activeAdapter.name}`,
            original: text.slice(0, 200),
            proposed: suggestion,
            rationale: `Adapter: ${activeAdapter.name}`,
            confidence: 0.7,
            createdAt: new Date().toISOString(),
          });
          aiCalls++;
          tokensConsumed += suggestion.length;
        }
      } catch (err) {
        logger.warn('StyleAdaptedWriterAgent: generation failed for section', {
          sectionId: section.id,
          err,
        });
      }
    }

    return {
      reviewItems,
      metrics: {
        aiCalls,
        tokensConsumed,
        durationMs: this.elapsed(startTime),
        itemsFound: reviewItems.length,
        itemsAccepted: 0,
        itemsRejected: 0,
      },
      agentOutput: {
        adapterId: activeAdapter.id,
        adapterName: activeAdapter.name,
        suggestionsGenerated: reviewItems.length,
      },
    };
  }
}
