#!/usr/bin/env tsx
// QNBS-v3: PR4 i18n — generates docs/i18n/TRANSLATION_STATUS.md, the per-locale quality dashboard.
// Unlike scripts/i18n-quality-report.mjs (a quick .mjs that cannot see the typed registry), this is a
// TS script run via tsx so it can import the SSOT `status` tier (production / near-production / beta)
// and combine it with computed coverage. Run: `pnpm run i18n:status`. Read-only except the doc it writes.
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { LOCALES, type LocaleStatus } from '../i18n/locales';

const ROOT = join(import.meta.dirname, '..');
const LOCALES_DIR = join(ROOT, 'locales');
const REF = 'en';
// QNBS-v3: 'help' is excluded — the dashboard reports *UI* coverage, and help.json long-form content is
// intentionally English fallback for non-Production locales (helpFallback). Including it would conflate
// a deliberate-English module with untranslated UI and understate real UI coverage (CodeAnt).
const MODULES = readdirSync(join(LOCALES_DIR, REF))
  .filter((f) => f.endsWith('.json'))
  .map((f) => f.slice(0, -5))
  .filter((m) => m !== 'help');

const PLACEHOLDER = /\{\{\s*([\p{L}\d_]+)\s*\}\}/gu;
// QNBS-v3: narrow the optional regex capture group via a guard instead of `as string`.
const tokens = (s: string): Set<string> => {
  const out = new Set<string>();
  for (const m of s.matchAll(PLACEHOLDER)) {
    if (m[1] !== undefined) out.add(m[1]);
  }
  return out;
};
const sameTokens = (a: Set<string>, b: Set<string>): boolean =>
  a.size === b.size && [...a].every((x) => b.has(x));

// QNBS-v3: type-guard so a non-object JSON value can't be treated as a translation map (no `as`).
const isRecord = (v: unknown): v is Record<string, unknown> =>
  typeof v === 'object' && v !== null && !Array.isArray(v);

function load(lang: string, mod: string): Record<string, unknown> {
  const p = join(LOCALES_DIR, lang, `${mod}.json`);
  if (!existsSync(p)) return {};
  const parsed: unknown = JSON.parse(readFileSync(p, 'utf8'));
  return isRecord(parsed) ? parsed : {};
}

interface Row {
  code: string;
  status: LocaleStatus;
  coverage: number;
  placeholderIssues: number;
}

const rows: Row[] = [];
for (const locale of LOCALES) {
  if (locale.code === REF) continue;
  let total = 0;
  let untranslated = 0;
  let placeholderIssues = 0;
  for (const mod of MODULES) {
    const en = load(REF, mod);
    const loc = load(locale.code, mod);
    for (const [k, enVal] of Object.entries(en)) {
      if (typeof enVal !== 'string') continue;
      total++;
      const locVal = loc[k];
      // QNBS-v3: a missing or non-string localized value is NOT translated — count it as untranslated
      // rather than skipping it, otherwise coverage is overstated and a locale could be falsely
      // promoted. (Parity normally guarantees a string here; this guards the transient/edge case.)
      if (typeof locVal !== 'string') {
        untranslated++;
        continue;
      }
      if (locVal === enVal && enVal.trim().length > 2) untranslated++;
      if (!sameTokens(tokens(enVal), tokens(locVal))) placeholderIssues++;
    }
  }
  rows.push({
    code: locale.code,
    status: locale.status,
    coverage: total ? Math.round(((total - untranslated) / total) * 100) : 0,
    placeholderIssues,
  });
}

const TIER_LABEL: Record<LocaleStatus, string> = {
  production: '🟢 Production',
  'near-production': '🟡 Near-Production',
  beta: '🔵 Beta',
};

const byTier = (s: LocaleStatus) => LOCALES.filter((l) => l.status === s).map((l) => l.code);

const lines: string[] = [
  '# Translation Status Dashboard',
  '',
  '> Auto-generated by `pnpm run i18n:status` (`scripts/i18n-status-dashboard.ts`). Do not hand-edit.',
  '> Tier = the SSOT `status` in `i18n/locales.ts`; coverage = share of string values that differ from',
  '> the English source (brand/technical terms that are legitimately identical lower it slightly).',
  '',
  '## Tiers',
  '',
  '- **🟢 Production** — full key parity **and** translated `help.json`; ready for general use.',
  '- **🟡 Near-Production** — ≥96% UI string coverage, 0 placeholder-integrity issues; `help.json` still',
  '  English fallback (the remaining gap to Production). No native review yet.',
  '- **🔵 Beta** — key parity holds; UI is machine-translated or partially complete; `help.json` English.',
  '',
  `Production: ${byTier('production').join(', ')} · Near-Production: ${byTier('near-production').join(', ')} · Beta: ${byTier('beta').join(', ')}`,
  '',
  '## Per-locale',
  '',
  '| Locale | Tier | UI coverage | Placeholder issues | Help |',
  '|--------|------|------------:|-------------------:|------|',
  `| ${REF} | ${TIER_LABEL.production} | 100% | 0 | native |`,
];
for (const r of rows.sort((a, b) => a.code.localeCompare(b.code))) {
  const help = LOCALES.find((l) => l.code === r.code)?.helpFallback ? 'English fallback' : 'native';
  lines.push(
    `| ${r.code} | ${TIER_LABEL[r.status]} | ${r.coverage}% | ${r.placeholderIssues} | ${help} |`,
  );
}
lines.push('');
lines.push(
  '> **Remaining work for full Production** (needs native human review): `help.json` long-form articles',
  '> for every non-core locale, plus a native pass over UI microcopy. See',
  '> [`BETA_TO_PRODUCTION_PLAYBOOK.md`](./BETA_TO_PRODUCTION_PLAYBOOK.md).',
  '',
);

writeFileSync(join(ROOT, 'docs', 'i18n', 'TRANSLATION_STATUS.md'), `${lines.join('\n')}\n`, 'utf8');
console.log(`[i18n-status] wrote docs/i18n/TRANSLATION_STATUS.md (${rows.length + 1} locales)`);
